name: rick_and_morty_verse
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  graphql_flutter: ^5.0.0
  freezed_annotation: ^0.14.2
  json_serializable: ^4.1.3
  dartz: ^0.10.0-nullsafety.2
  material_design_icons_flutter: 5.0.5955-rc.1
  hydrated_bloc: ^7.0.1
  google_fonts: ^2.1.0
  cached_network_image: ^3.0.0
  

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0
  freezed: ^0.14.2
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
  generate: true
